# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: 'Self-Help'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0' 
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet build --configuration Release
    displayName: 'Build Project'

  - script: dotnet test --configuration Release
    displayName: 'Run Unit Tests'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: drop