// <auto-generated />
using System;
using DisasterAlleviation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DisasterAlleviation.Migrations
{
    // Ensure the class inherits from a suitable base class that contains the BuildTargetModel method
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241001192102_updateprof")]
    partial class updateProf : Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Existing code
        }
    }
}
