using System.ComponentModel.DataAnnotations;

namespace DisasterAlleviation.Models
{
    public class Donation
    {
        public int DonationId { get; set; } // Auto-generated by the database

        [Required(ErrorMessage = "Resource Type is required")]
        public string ResourceType { get; set; } // e.g., food, clothing, medical supplies, other

        [Required(ErrorMessage = "Category is required")]
        public string NameOfItem { get; set; } // Specific category of the resource type (e.g., food: canned goods, clothing: winter)


        [Required(ErrorMessage = "Date is required")]
        public DateTime Date { get; set; } // Date of donation

        [Required(ErrorMessage = "Number of Items is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Must be at least 1 item")]
        public int NumberOfItems { get; set; } // Quantity of items donated

       
        [Required(ErrorMessage = "Description is required")]
        public string Description { get; set; } // Description of each item donated

        public string Status { get; set; } // e.g., pending, distributed
    }


}
