using System.ComponentModel.DataAnnotations;

namespace DisasterAlleviation.Models
{
    public class Donation
    {
        public int DonationId { get; set; } // Auto-generated by the database

        [Required(ErrorMessage = "Resource Type is required")]
        public string ResourceType { get; set; } 

        [Required(ErrorMessage = "Category is required")]
        public string NameOfItem { get; set; }


        [Required(ErrorMessage = "Date is required")]
        public DateTime Date { get; set; } 

        [Required(ErrorMessage = "Number of Items is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Must be at least 1 item")]
        public int NumberOfItems { get; set; } 

       
        [Required(ErrorMessage = "Description is required")]
        public string Description { get; set; } 

        public string Status { get; set; } 
    }


}
