using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public class IncidentReport
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IncidentId { get; set; } // This will be auto-generated by the database


    [Required(ErrorMessage = "Incident type is required.")]
    public string IncidentType { get; set; }

    [Required(ErrorMessage = "Location is required.")]
    [StringLength(100, ErrorMessage = "Location cannot be longer than 100 characters.")]
    public string Location { get; set; }

    [Required(ErrorMessage = "Severity is required.")]
    public string Severity { get; set; }

    [Required(ErrorMessage = "Description is required.")]
    [StringLength(500, ErrorMessage = "Description cannot be longer than 500 characters.")]
    public string Description { get; set; }

    public DateTime ReportDate { get; set; }
}
